name: Build Program

# Trigger on version tags like v1.0.0
on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Install Qt
    - name: Install Qt
      id: install_qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        cache: 'true'
        dir: '${{ github.workspace }}/build'
        version: '6.8.3'

    # Configure CMake
    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    # Build project
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    # Package as AppImage
    - name: Qt to AppImage
      id: appimage
      uses: Kidev/Qt-AppImage@v0.0.8
      with:
        install_folder: '${{github.workspace}}/build/Qt/6.8.3'
        app_name: 'lbox-linux-install-helper'
        comment: 'Install Helper for LMAOBOX'
        category: 'Utility'
        icon: 'icon.png'

    # Extract version from the Git tag
    - name: Get Version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    # Create and upload GitHub Release
    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.appimage.outputs.appimage }}
        name: LinuxInstallHelper ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
