name: Build Program

# Trigger on version tags like v1.0.0
#on:
  #push:
    #tags:
      #- 'v*'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    - name: Install FUSE
      run: sudo apt-get update && sudo apt-get install -y fuse libfuse2

    # Install Qt
    - name: Install Qt
      id: install_qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        cache: 'true'
        version: '6.8.3'

    - name: Verify Qt Path
      run: |
        if [ ! -d "/home/runner/work/lbox-linux-install-helper/Qt/6.8.3/gcc_64" ]; then
          echo "Qt directory not found!"
          exit 1
        fi

    # Configure CMake
    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    # Build project
    - name: Build
      run: |
         cmake --build build --target all

    # Package as AppImage
    - name: Qt to AppImage
      id: appimage
      uses: Kidev/Qt-AppImage@v0.0.8
      with:
        install_folder: '${QT_ROOT_DIR}'
        app_name: 'linux-helper'
        comment: 'Install Helper for LMAOBOX'
        category: 'Utility'
        icon: 'icon.png'
        binary: 'lbox-linux-install-helper'

    # Extract version from the Git tag
    - name: Get Version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    # Create and upload GitHub Release
    - name: Create/Update GitHub Pre-release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: "Nightly Build"
        prerelease: true
        overwrite_files: true
        files: ${{ steps.appimage.outputs.appimage }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
