name: Build Program

# Will trigger when a commit is tagged 'v*' (v1.0.0 for example)
on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        dir: '${{github.workspace}/build'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Qt to AppImage
      uses: Kidev/Qt-AppImage@v0.0.8
      with:
        install_folder: '${{github.workspace}}/build/Qt'
        app_name: 'LinuxHelper'
        comment: 'Install Helper for LMAOBOX'
        category: 'Utility'
        icon: 'icon,png'

      # Extract version from the commit tag
    - name: Get Version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.appimage.outputs.appimage }}
        name: LinuxInstallHelper ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
